project_id = "xwykwysxaqsyyizustyr"

[functions.analyze-skills]
verify_jwt = false

[functions.compare-skills]
verify_jwt = false

[functions.get-job-skills]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.ocr-transcript]
verify_jwt = false
