project_id = "xwykwysxaqsyyizustyr"

[functions.analyze-skills]
verify_jwt = false

[functions.compare-skills]
verify_jwt = false

[functions.get-job-skills]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
